### ISSUE TITLE
Swift 项目一些 Error

### ISSUE THREAD

**Issue by lukailun** [easemob/easemob-uikit-ios#8]
通过 CocoaPod 集成，运行项目报错。

<img width="400" alt="企业微信20240606-140031@2x" src="https://github.com/easemob/easemob-uikit-ios/assets/20470157/e6854e83-7321-40ea-9a7b-24b58a2d946b">

MessageCell.swift:67:70: Initializing from a metatype value must reference 'init' explicitly

TextMessageCell.swift:70:21: Initializer 'init(coder:)' with Objective-C selector 'initWithCoder:' conflicts with initializer 'init(coder:)' from superclass 'MessageCell' with the same Objective-C selector

还有好多 Initializer 'init(coder:)' with Objective-C selector 'initWithCoder:' conflicts with initializer 'init(coder:)' from superclass 'MessageCell' with the same Objective-C selector 的错误。

能帮看看如何处理吗？

**Comment by zjc19891106** [comment]
新建个Swift项目试试
不行可以看看，https://github.com/easemob/easemob-demo-ios/tree/SwiftDemo

**Comment by zjc19891106** [comment]
你建的OC工程吗？

**Comment by lukailun** [comment]
Swift 项目，我新建个项目试下。

**Comment by lukailun** [comment]
原因是我 format 了下项目里的代码，导致 format 出了问题。SDK 本身没问题。剔除掉 format 第三方，就可以了。
